### ISSUE TITLE
OrdersGetRequest query

### ISSUE THREAD

**Issue by mstojanovv** [paypal/Checkout-PHP-SDK#10]
Hello.
I have query related to get order API.
Regards.

**Comment by rajarampadmanathan** [comment]
Hi @mstojanovv - We're working on it. Fix is scheduled in the week of March 11th.

**Comment by mstojanovv** [comment]
Great, thanks.

**Comment by rajarampadmanathan** [comment]
Hi @mstojanovv - We're working on the release. It should be released before end of this week.

**Comment by mstojanovv** [comment]
Hi @rajarampadmanathan 

Can you tell me if this is happening only on the sandbox so I can proceed with my implementation without waiting for new release?

Regards.

**Comment by rajarampadmanathan** [comment]
It doesn't need any SDK fix. I needs fix in our API. Our API team already fixed this and working on validating this. I will have release verified tomorrow.
You can proceed with implementation, since it doesn't any change in client side to resolve this issue.

**Comment by rajarampadmanathan** [comment]
Hi @mstojanovv - This is fixed now and i validated the fix in SBX. Please check validate and let me know in case of any issues.

Thanks for your patience.

**Comment by ganeshramc** [comment]
Hi @mstojanovv, we hope your issue is resolved! If it has not been or if you have any other questions, we'll keep this issue open for 7 days. We'll be closing the issue after that. Thanks 😄
