### ISSUE TITLE
Impossible to use EUR in checkout

### ISSUE THREAD

**Issue by jokamax** [paypal/Checkout-PHP-SDK#11]
Hi,

I use this Api to create Order (with sandbox) : 

```
$request = new OrdersCreateRequest();
$request->prefer('return=representation'); 
$request->body = self::buildRequestBody();
```
And product : 

```
private static function buildRequestBody()
    {
        return array(
            "intent" => "CAPTURE",
            "purchase_units" => [[
                "reference_id" => "buy_mon_id1",    
                'description' => "1 Mois d'abonnement à SB Premium", 
                "amount" => [
                    "value" => "5.99",
                    "currency_code" => "EUR"
                ]
            ]],
            "application_context" => [
                "brand_name" => 'SB',
                "cancel_url" => "",
                "return_url" => ""
            ]
        );
    }
```
Business Sandbox associated account has EUR as PRIMARY CURRENCY

But when I use, I get error : 
**Error: Expected currency from order api call to be USD, got EUR. Please ensure you are passing currency=EUR to the sdk**

Impossible to found where to force EUR to SDK.
If I use USD, it works...

Thanks by advance

Jonathan

**Comment by jokamax** [comment]
Wow, after two days search, I've just have found : 
This is in the URL of the JS : https://www.paypal.com/sdk/js?currency=EUR
Maybe, you can update a little documentation to associate button URL Currency and Product Currency :-)

**Comment by AlexeiaW** [comment]
> Wow, after two days search, I've just have found :
> This is in the URL of the JS : https://www.paypal.com/sdk/js?currency=EUR
> Maybe, you can update a little documentation to associate button URL Currency and Product Currency :-)

Yeah, it is not obvious at all

**Comment by avatec** [comment]
For me it is not working. Trying for PLN - and sets currency=PLN in url, but i have errors. Before that i was using DOCS method - currency_code: 'PLN' - without results.

`<script src="https://www.paypal.com/sdk/js?currency=PLN&client-id={$config.paypal_client_id}"></script>
        <div id="paypal-button-container"></div>
        <script>
            paypal.Buttons({
                createOrder: function (data, actions) {
                    return actions.order.create({
                        purchase_units: [
                            {
                                recipient_type: 'EMAIL',
                                amount: {
                                    reference_id: '{$reference_id}',
                                    currency_code: 'PLN',
                                    value: {$data.price_sum}
                                },
                                shipping: {
                                    address: {
                                        name: "{$data.first_name} {$data.last_name}"
                                    }
                                }
                            }
                        ]
                    });
                },
                onApprove: function (data, actions) {
                    return actions.order.capture().then(function (details) {
                        console.log(details);
                        alert('Transaction completed by ' + details.payer.name.given_name);
                    });
                }
            }).render('#paypal-button-container'); // Display payment options on your web page
        </script>`

 
<img width="1637" alt="Zrzut ekranu 2020-06-19 o 16 30 16" src="https://user-images.githubusercontent.com/272826/85143557-2f5a6a00-b24a-11ea-9da3-2e2bb44460f6.png">

**Comment by avatec** [comment]
I found solution. Message should be to append &currency=PLN after ?client-id. In this order it works.
