### ISSUE TITLE
composer install problem

### ISSUE THREAD

**Issue by kslr** [paypal/Checkout-PHP-SDK#13]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: braintree/braintreehttp[0.3.0, 0.2.4].
    - Can only install one of: braintree/braintreehttp[0.3.0, 0.2.4].
    - Can only install one of: braintree/braintreehttp[0.3.0, 0.2.4].
    - paypal/paypal-checkout-sdk 1.0.0 requires braintree/braintreehttp 0.3.0 -> satisfiable by braintree/braintreehttp[0.3.0].
    - Installation request for paypal/paypal-checkout-sdk 1.0.0 -> satisfiable by paypal/paypal-checkout-sdk[1.0.0].
    - Installation request for braintree/braintreehttp (locked at 0.2.4) -> satisfiable by braintree/braintreehttp[0.2.4].

Installation failed, reverting ./composer.json to its original content.

Can only install ?  :confused:

**Comment by rajarampadmanathan** [comment]
Will check this and get back to you

**Comment by kslr** [comment]
fix
