### ISSUE TITLE
Patch Order throws error while updating shipping costs

### ISSUE THREAD

**Issue by hansrouge** [paypal/Checkout-PHP-SDK#14]
Hi there,

I want to change the shipping price when the customer updates his shipping-address within paypal. But I get this error as soon I change the address in the Paypal-Popup:

> <b>Fatal error</b>:  Uncaught BraintreeHttp\HttpException: 
{"name":"UNPROCESSABLE_ENTITY","details":
	[
		{"issue":"VALIDATION_ERROR","description":"VALIDATION_ERROR"}
	],
	"message":"The requested action could not be performed, semantically incorrect, or failed business validation.",
	"debug_id":"673d649420f74",
	"links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-VALIDATION_ERROR","rel":"information_link"}
]} in /var/www/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php:185
Stack trace:
#0 /var/www/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php(97): BraintreeHttp\HttpClient-&gt;parseResponse(Object(BraintreeHttp\Curl))
#1 [...]
#2 [...]
#3 {main}
  thrown in <b>/var/www/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php</b> on line <b>185</b><br/>

I cannot find the error "VALIDATION_ERROR" in the documentation :-/

What I do is this:

JS:
```
[...]
onShippingChange: function(data, actions) {
      	fetch(ajax, {
			    method: 'post',
			    body: new URLSearchParams({'do':'getShippingPricePaypalPlus','country':data.shipping_address.country_code,'id':data.orderID}),
			    headers: {
			    	'Accept': 'application/json',
			      'content-type': 'application/x-www-form-urlencoded; charset=UTF-8'
			    }
			  }).then(function(res) {
			    return res.text();
			  }).then(function(data) {
			  	if(!data)
			  		return actions.reject();
			  	return actions.resolve();
			  });
    	}
[...]
```

PHP:
```
    $client = self::ppClient();
    $request = new OrdersPatchRequest($p->orderID);
		$request->body = [
						 [
            		'op' => 'replace',
                'path' => '/intent',
                'value' => 'CAPTURE',
             ],[
	              'op' => 'replace',
	              'path' => '/purchase_units/@reference_id==\'default\'/amount',
		            'value' => [
	            			'value' => $r->priceToPay,
	            			'currency_code' => $this->shop->mC->iso,
	            			'breakdown' => [
		            				'item_total' => [
		            					'currency_code' => $this->shop->mC->iso,
			          					'value' => $r->priceGoods
		            				],
		            				'shipping' => [
		            					'currency_code' => $this->shop->mC->iso,
			          					'value' => $r->priceShipping
		            				],
		            				'tax_total' => [
		            					'currency_code' => $this->shop->mC->iso,
			          					'value' => $r->priceTax
		            				]
		            		]
	        			]
	         ]
        ];	
  	$client->execute($request);
  	$response = $client->execute(new OrdersGetRequest($p->id));
  	return $response->result;
```

I double checked the values and variables - they are all correct.

I used the example in the documentation (https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/). 

The "default"-value in "path" is correct as well - I checked it by 

Do you have any idea what I am doing wrong?
Any help is appreciated!

Kind regards
hansrouge

[-----]
This part is just for your interest:
Though I would prefer to use the PHP solution, I tryed changing my code to a pure JS solution, which throws an error as well:

```
onShippingChange: function(data, actions) {
      	fetch(ajax, {
			    method: 'post',
			    body: new URLSearchParams({'do':'getShippingPricePaypalPlus',
			    													 'country':data.shipping_address.country_code,
			    													 'id':data.orderID}),
			    headers: {
			    	'Accept': 'application/json',
			      'content-type': 'application/x-www-form-urlencoded; charset=UTF-8'
			    }
			  }).then(function(res) {
			    return res.text();
			  }).then(function(data) {
			  	if(!data)
			  		return actions.reject();				 
			   return actions.order.patch([
            	{
	              op: 'replace',
	              path: '/purchase_units/@reference_id==\'default\'/amount',
	              value: {
	                currency_code: mC.iso,
	                value: data.priceToPay,
	                breakdown: {
	                  item_total:{
	                  	currency_code: mC.iso,
                      value: data.priceGoods
	                	},
	                	shipping: {
                      currency_code: mC.iso,
                      value: data.shippingPrice
	                  },
	                  tax_total: {
	          					currency_code: mC.iso,
	          					value: data.priceTax
		            		}
	                }
		          	}
		          }
		        ]);
			  });
    	}
```
Error: "Error: Order could not be patched" and I get a "POST https://www.sandbox.paypal.com/smart/api/order/6WL53986XG2374724/patch 400 (Bad Request)" in the console.

**Comment by rajarampadmanathan** [comment]
Hi, By any chance do you have the paypal-debug-id for this request?

**Comment by hansrouge** [comment]
Sure: 1c90c85d8114 or 673d649420f74
I tried it a few times, so there are a few ;)

**Comment by rajarampadmanathan** [comment]
I can see in create order you're passing SKU as "". In create order there is no check but patch order validates it and throws error if it is empty.

For now as a workaround, you can pass sku value as `non empty string` or `null` instead of empty string.

@rsdighe76 - We need to analyze this and fix in the API

**Comment by hansrouge** [comment]
Wow, thank you for your fast reply!
Now, the error is gone :)

But, the amount is not updated live in the Paypal Window:
The return of patch:
```
{
	"id":"2RA11176UY042594P",
  "intent":"CAPTURE",
  "purchase_units":[
  	{
  		"reference_id":"default",
  		"amount":
  		{
  			"currency_code":"EUR",
  			"value":"325.00",
  			"breakdown":
  			{
  				"item_total":
  				{
  					"currency_code":"EUR",
  					"value":"256.30"
  				},
  				"shipping":
  				{
  					"currency_code":"EUR",
  					"value":"16.81"
  				},
  				"tax_total":
  				{
  					"currency_code":"EUR",
  					"value":"51.89"
  				}
  			}
  		},
  		"payee":
  		{
  			"email_address":"xxx",
  			"merchant_id":"xxx"
  		},
  		"items":[
  			{
  				"name":"Product",
  				"unit_amount":
  				{
  					"currency_code":"EUR",
  					"value":"256.30"
  				},
  				"quantity":"1",
  				"sku":"1234"
  			}
  		]
  	}
  ],
  "create_time":"2019-04-12T08:01:41Z",
  "links":[
  	{
  		"href":"https:\/\/api.sandbox.paypal.com\/v2\/checkout\/orders\/2RA11176UY042594P",
  		"rel":"self",
  		"method":"GET"
  	},
  	{
  		"href":"https:\/\/www.sandbox.paypal.com\/checkoutnow?token=2RA11176UY042594P",
  		"rel":"approve",
  		"method":"GET"
  	},
  	{
  		"href":"https:\/\/api.sandbox.paypal.com\/v2\/checkout\/orders\/2RA11176UY042594P\/capture",
  		"rel":"capture",
  		"method":"POST"
  	}
  ],
  "status":"CREATED"
}
```
The Shipping Amount is correct.
But in Paypal the shipping amount doesn't change to 16,81 ("Versand" in German) and the total amount doesn't change as well ("Summe"):
<img width="348" alt="payment" src="https://user-images.githubusercontent.com/11441510/56022276-922da880-5d0b-11e9-8273-7ae01931d1fe.png">

Changing the country to somewhere I do not ship to, works fine. There I see a prompt something like "... doesn't support your country".

**Comment by rajarampadmanathan** [comment]
For this specific token, i can see 4 patch calls. And the latest one patched the amount as below that is what shown in the checkout review page.
`{"value":309.95,"currency_code":"EUR","breakdown":{"item_total":{"currency_code":"EUR","value":256.3},"shipping":{"currency_code":"EUR","value":4.16},"tax_total":{"currency_code":"EUR","value":49.49}}}`
