### ISSUE TITLE
webhooks

### ISSUE THREAD

**Issue by liedekef** [paypal/Checkout-PHP-SDK#17]
Currently I don't see a way to define/list/delete webhooks in the API v2. It seems a little weird that I would need this API for checkout and the API v1 for webhook management ...
Is there a way to handle this?

**Comment by bmewburn** [comment]
Any response on this? The readme in https://github.com/paypal/PayPal-PHP-SDK recommends to use Checkout-PHP-SDK but there hasn't been any commits for months and the functionality is very limited.

**Comment by liedekef** [comment]
Any response on this?

**Comment by liedekef** [comment]
It seems this API is not production ready at all and no real development has been happening for months. Is this still a supported API? If so, when will webhooks be available?

**Comment by tiffanyrzhou** [comment]
this SDK does not support this particular API - it only supports v2/payments and v2/checkout/orders

**Comment by bmewburn** [comment]
@tiffanyrzhou would you mind linking to an alternative library then for webhooks? Checkout-PHP-SDK won't support it, https://github.com/paypal/PayPal-PHP-SDK v1 is deprecated and archived and v2 is now also archived. Are you dropping php support?

**Comment by liedekef** [comment]
> @tiffanyrzhou would you mind linking to an alternative library then for webhooks? Checkout-PHP-SDK won't support it, https://github.com/paypal/PayPal-PHP-SDK v1 is deprecated and archived and the in development v2 is now also archived. Are you dropping support for php sdks?

I agree, would also like a solution for this.
