### ISSUE TITLE
BraintreeHttp IOException

### ISSUE THREAD

**Issue by tuxnull** [paypal/Checkout-PHP-SDK#18]
I get this error which occurs while trying to run `$client->execute($request)`

here's the total error:
`Fatal error: Uncaught BraintreeHttp\IOException: SSL certificate problem: unable to get local issuer certificate in C:\xampp\php\vendor\braintree\braintreehttp\lib\BraintreeHttp\HttpClient.php:167 Stack trace: #0 C:\xampp\php\vendor\braintree\braintreehttp\lib\BraintreeHttp\HttpClient.php(97): BraintreeHttp\HttpClient->parseResponse(Object(BraintreeHttp\Curl)) #1 C:\xampp\php\vendor\paypal\paypal-checkout-sdk\lib\PayPalCheckoutSdk\Core\AuthorizationInjector.php(37): BraintreeHttp\HttpClient->execute(Object(PayPalCheckoutSdk\Core\AccessTokenRequest)) #2 C:\xampp\php\vendor\paypal\paypal-checkout-sdk\lib\PayPalCheckoutSdk\Core\AuthorizationInjector.php(29): PayPalCheckoutSdk\Core\AuthorizationInjector->fetchAccessToken() #3 C:\xampp\php\vendor\braintree\braintreehttp\lib\BraintreeHttp\HttpClient.php(64): PayPalCheckoutSdk\Core\AuthorizationInjector->inject(Object(PayPalCheckoutSdk\Orders\OrdersCreateRequest)) #4 D:\webspace\nfc\do_order.php(58): BraintreeHttp\HttpClient->execute(Object(PayPalCheckoutSdk\Orders\OrdersCreateR in C:\xampp\php\vendor\braintree\braintreehttp\lib\BraintreeHttp\HttpClient.php on line 167`

**Comment by tuxnull** [comment]
After a bit of researching, I found out that the locally stored cURL SSL Certificate database had to be updated by downloading the latest from https://curl.haxx.se/docs/caextract.html and adding the following lines to the php.ini:
`curl.cainfo="C:\xampp\cacert.pem"`
`openssl.cafile="C:\xampp\cacert.pem"`

**Comment by ganeshramc** [comment]
That's great @tuxnull. If you've resolved the problem, can we close it?

**Comment by tuxnull** [comment]
Sure can!
