### ISSUE TITLE
Syntax Error in HttpClient.php

### ISSUE THREAD

**Issue by sperro** [paypal/Checkout-PHP-SDK#19]
Using composer I installed Checkout-PHP-SDK which extends BraintreeHttp.
When verifying the transaction in the GetOrder class I'm getting this error.
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php on line 38

**Comment by fluxxus** [comment]
@sperro Did you manage to resolve this? 

I am getting different errors than yours, can you tell me how are you verifying the transaction?

Following the docs was not very helpful, it is not clear to me how to verify the transaction based on the example code provided in the docs.

**Comment by bvmanil** [comment]
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in      
Braintree/vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php on line 39
how to resolve it my php version is 5.4.45

**Comment by omar09091993** [comment]
> Using composer I installed Checkout-PHP-SDK which extends BraintreeHttp.
> When verifying the transaction in the GetOrder class I'm getting this error.
> Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /vendor/braintree/braintreehttp/lib/BraintreeHttp/HttpClient.php on line 38

**Comment by tiffanyrzhou** [comment]
This sdk no longer uses BraintreeHttp. Please share if the same problems occurs in paypalhttp. Thanks.

**Comment by kaiyunj** [comment]
Just did with paypalhttp, exactly the same error with my php 5.4.16
