### ISSUE TITLE
Best way to check that the order has been paid?

### ISSUE THREAD

**Issue by Rattone** [paypal/Checkout-PHP-SDK#20]
What is the correct way, with this SDK, to check that the order has actually been paid once the user returns to the site?
I've to capture the order when user come back and do some checks on the amount paied?
Or should I use the webhook for this purpose (not available in this SDK)?

**Comment by ganeshramc** [comment]
You can do a get on order and check the status. Once it says `APPROVED` you can capture the order. Check the GetOrder.php example!

**Comment by Rattone** [comment]
> You can do a get on order and check the status. Once it says `APPROVED` you can capture the order. Check the GetOrder.php example!

Thanks for reply.

I've other questions:
- If the order capture is successful, can I consider the transaction successful, without any problems?
So isn't this enough, without getting order? (my goal is to automatically approve the order on my website)
- There is a way to make a payment, with this SDK, without having to capture it?

**Comment by ganeshramc** [comment]
Yes! If you can capture it, it means it has succeeded. You do not need to do a get on order. After approve you can directly capture. 
To make automatic payments, you have to set up billing-plans or subscriptions which is not part of this SDK yet.

**Comment by Rattone** [comment]
@ganeshramc I don't want to make automatic recurring payments.
I want mark the order (on my ecommerce) as "paid" when the user has actually paid, the same thing I did with the IPN in the previous version of paypal checkout...

**Comment by Rattone** [comment]
@ganeshramc I don't want to make automatic recurring payments. I want mark the order (on my ecommerce) as "paid" when the user has actually paid on paypal, the same thing I did with the IPN in the previous version of paypal checkout...

What is the correct way to do this with this SDK?

Thanks again for the answers

**Comment by ganeshramc** [comment]
@Rattone, Once you capture the order, you can mark it as paid right? I'm not sure I understand your requirement.

**Comment by NanoCellWebDesign** [comment]
@Rattone when you set up your payment save the payment id to a database
`$payment = new Payment();`
        `$payment->setExperienceProfileId($webProfileId); // no shipping`
     ` $payment->setIntent("sale")`
            `->setPayer($payer)`
           ` ->setRedirectUrls($redirectUrls)`
           ` ->setTransactions(array($transaction));`
       ` try {`
         `   $payment->create($apiContext);`
inside of the try-catch with `$payment->getId();`

then in the execute payment after the try-catch 
 `try {`
           ` $result = $payment->execute($execution, $apiContext);`
        `} catch (Exception $ex) {`
            `echo $ex;`
            `exit(1);`
       `}`

find the database entry using the payment id using
`$payment->payer->payer_info->payer_id();`

then update that entry field for the state with
`$payment->state;`

**Comment by Rattone** [comment]
> @Rattone when you set up your payment save the payment id to a database
> `$payment = new Payment();`
> `$payment->setExperienceProfileId($webProfileId); // no shipping`
> ` $payment->setIntent("sale")`
> `->setPayer($payer)`
> ` ->setRedirectUrls($redirectUrls)`
> ` ->setTransactions(array($transaction));`
> ` try {`
> ` $payment->create($apiContext);`
> inside of the try-catch with `$payment->getId();`
> 
> then in the execute payment after the try-catch
> `try {`
> ` $result = $payment->execute($execution, $apiContext);`
> `} catch (Exception $ex) {`
> `echo $ex;`
> `exit(1);`
> `}`
> 
> find the database entry using the payment id using
> `$payment->payer->payer_info->payer_id();`
> 
> then update that entry field for the state with
> `$payment->state;`

Sorry for the late reply... your example seems to come from [https://github.com/paypal/rest-api-sdk-php/](paypal/rest-api-sdk-php), I am right?

**Comment by NanoCellWebDesign** [comment]
> > @Rattone when you set up your payment save the payment id to a database
> > `$payment = new Payment();`
> > `$payment->setExperienceProfileId($webProfileId); // no shipping`
> > ` $payment->setIntent("sale")`
> > `->setPayer($payer)`
> > ` ->setRedirectUrls($redirectUrls)`
> > ` ->setTransactions(array($transaction));`
> > ` try {`
> > ` $payment->create($apiContext);`
> > inside of the try-catch with `$payment->getId();`
> > then in the execute payment after the try-catch
> > `try {`
> > ` $result = $payment->execute($execution, $apiContext);`
> > `} catch (Exception $ex) {`
> > `echo $ex;`
> > `exit(1);`
> > `}`
> > find the database entry using the payment id using
> > `$payment->payer->payer_info->payer_id();`
> > then update that entry field for the state with
> > `$payment->state;`
> 
> @NanoCellWebDesign Sorry for the late reply... your example seems to come from [https://github.com/paypal/rest-api-sdk-php/](paypal/rest-api-sdk-php), I am right?

i believe so
