### ISSUE TITLE
"shipping_preferences" instead of "shipping_preference"

### ISSUE THREAD

**Issue by Rattone** [paypal/Checkout-PHP-SDK#21]
In the [PayPal DOC](https://developer.paypal.com/docs/api/orders/v2/#definition-application_context) this field 'shipping_preferences' is singular.

https://github.com/paypal/Checkout-PHP-SDK/blob/9307dc246780d999df1b76d7d01085d5e2c34aa1/samples/CaptureIntentExamples/CreateOrder.php#L30

https://github.com/paypal/Checkout-PHP-SDK/blob/9307dc246780d999df1b76d7d01085d5e2c34aa1/samples/AuthorizeIntentExamples/CreateOrder.php#L28

**Comment by ganeshramc** [comment]
Thanks for reporting this @Rattone! We had updated our APIs since this release and are working on fixing existing samples and new samples which will be released soon

**Comment by ganeshramc** [comment]
This is updated now. Thanks for your feedback!
