### ISSUE TITLE
Paypal integration with (Angular or Javascript ) and PHP

### ISSUE THREAD

**Issue by ferhado** [paypal/Checkout-PHP-SDK#23]
Have any one a clear example how to integrate PayPal in (Angular or Javascript ) with PHP as backend?
I'm not able to understand the existing example and PayPal documentation

**Comment by giantslayer21** [comment]
Have you found a solution to your request ??

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback.
This is currently our official integration guide: https://developer.paypal.com/docs/business/checkout/set-up-standard-payments We will look into improving these integration guides, as well as providing additional samples for integration guidance.
