### ISSUE TITLE
Capture order Returns `400 bad request`

### ISSUE THREAD

**Issue by minororange** [paypal/Checkout-PHP-SDK#28]
I test in the sandbox, It's everything ok. But, I found this question in the production env.

The code :

```php
public function captureOrder($orderId)
    {
        try {
            $request = new OrdersCaptureRequest($orderId);

            $client = PayPalClient::client();
            $response = $client->execute($request);

            if ($response->statusCode != 201) {
                throw new PaypalErrorException('Failure to capture an order of paypal.', 3003, $response);
            }

            return $response;
        } catch (HttpException $exception) {
            $message = $client->encoder->deserializeResponse($exception->getMessage(), $exception->headers) . ' paypal ID:' . $orderId;

            throw new PaypalErrorException('Failure to capture an order of paypal.', 3003, $message);
        }
    }
```

Paypal response:

```HTML
<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;&#35;7&#46;55eb7068&#46;1568863332&#46;44f5696c
</BODY>
</HTML>
```

**Comment by ganeshramc** [comment]
Thanks for reaching out @minororange! I would need a little bit more details. But to start off, could you add `$request->headers["Content-Type"]="application/json";` before your $client declaration

**Comment by minororange** [comment]
Your SDK client has been add the headers:

![image](https://user-images.githubusercontent.com/25793112/65211761-6bea1100-dad2-11e9-822c-f8d3a268f298.png)

**Comment by minororange** [comment]
![image](https://user-images.githubusercontent.com/25793112/65211787-8a500c80-dad2-11e9-812e-320529d5ea1a.png)

**Comment by ganeshramc** [comment]
Yes. I am trying to isolate what the issue could be. Please try that if you can. PayPal response should be in json format.

**Comment by minororange** [comment]
okay,I has added it. And I contacted the Paypal Help Center,They will create a test order later

**Comment by minororange** [comment]
I found the mistake,I modify the `baseUrl` in the `PayPalEnvironment` , The real uri is:https://api.paypal.com, but mine is: https://www.paypal.com.

And in the sandbox, `https://www.sandbox.paypal.com` and `https://api.sandbox.com` are both ok.
