### ISSUE TITLE
Missing file autoload.php

### ISSUE THREAD

**Issue by Jens1278** [paypal/Checkout-PHP-SDK#30]
The examples require the file autoload.php. Neither the file autoload.php nor the directory vendor exists in this repository! Without this file there is nothing that can be done with this SDK.

Where can I find the complete SDK?

**Comment by ganeshramc** [comment]
Hi, you should import the SDK from composer. Please take a look at https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/

**Comment by Jens1278** [comment]
This is not possible since composer is not available on the server of my web hosting provider. Publishing an incomplete SDK is useless and wastes just a lot of time of many people! So, either remove the SDK from Github or provide a working package that contains all files that it requires.

**Comment by ganeshramc** [comment]
Hi, thanks for your comments. So when installing an sdk or it's dependencies currently everyone uses this same method of installing them through composer. You should be able to list it as a dependency as well. On here is only for listing the sdk samples as well as for knowledge of how the SDK works. You should still be able to download this as well and use it. The samples are for reference so you might have to make minor modifications to it to work for your system.

**Comment by ganeshramc** [comment]
To add on, autoload.php only shows up when you do `composer install`. We cannot include autoload.php as it differs with every system and would break it for everyone else using this.

**Comment by Jens1278** [comment]
You mean it was possible to add all dependencies to the REST API SDK, that is much larger and more complex, but it is not possible to add it to this tiny package? Ok, I do this what probably most other people do, I use another payment provider!

**Comment by ganeshramc** [comment]
Currently all dependencies are listed here: https://github.com/paypal/Checkout-PHP-SDK/blob/develop/composer.json
`composer install` will install them.

**Comment by ganeshramc** [comment]
Please reach out to us if you have any other questions. Thanks!

**Comment by MSandro** [comment]
so this is not usable without composer? sad ...

**Comment by gt222cu** [comment]
> Similar to how we should not include node_modules in a JavaScript SDK on GitHub, we should not include vendor folder for PHP either. Thanks

Really? You are alienating a pile of developers and customers on hosted servers who are trying to upgrade their older PayPal applications.
I've spent two days trying to develop a portable set of SDK files that can be distributed without required dependencies using this SDK and I am giving up - my clients will be using Stripe from now on if they want to get away from the V1 API. Either that or ignore the SDK and use pure PHP/cURL.

Your documentation is sadly lacking and bears little resemblance to the code here. The docs mix and match your v2 SDK with the other PayPal SDKs until the endless, circular links gets my head spinning.

..and I've been integrating PayPal using PHP since 1998 so I think I may know something about what I'm doing here.

**Comment by MESWEB** [comment]
> Currently all dependencies are listed here: https://github.com/paypal/Checkout-PHP-SDK/blob/develop/composer.json
> `composer install` will install them.
> Similar to how we should not include node_modules in a JavaScript SDK on GitHub, we should not include vendor folder for PHP either. Thanks

Hi @tiffanyrzhou.
Yes it's very big reason:

My own loader

autoload.php 309 bytes

And here is composer:

composer.phar 1,874,955 bytes

1874955 - 293 = 1874369
1874369 * 100 / 293 = 639,816% oversized code
My own autoloader works very great without unnecessary code. Look for google there are lot info about minimize HTML code by deleting unused CSS or JS and many more so what's a reason why I should use composer which one is very big size.
