### ISSUE TITLE
Autoload PSR-4 failed

### ISSUE THREAD

**Issue by MESWEB** [paypal/Checkout-PHP-SDK#37]
### General information

* SDK/Library version: 1.0.1
* Environment: Sandbox
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: PHP Windows 10

### Issue description

I can't autoload files without composer.
**index.php**
```php
<?php

require __DIR__ . '\autoload.php';

use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;
// Creating an environment
$clientId = "xxx";
$clientSecret = "xxx";

$environment = new SandboxEnvironment($clientId, $clientSecret);
$client = new PayPalHttpClient($environment);
```
**autoload.php**
```php
<?php
/**
 * An example of a project-specific implementation.
 *
 * After registering this autoload function with SPL, the following line
 * would cause the function to attempt to load the \Foo\Bar\Baz\Qux class
 * from /path/to/project/src/Baz/Qux.php:
 *
 *      new \Foo\Bar\Baz\Qux;
 *
 * @param string $class The fully-qualified class name.
 * @return void
 */
spl_autoload_register(function ($class) {

    // project-specific namespace prefix
    $prefix = 'PayPalCheckoutSdk\\';

    // base directory for the namespace prefix
    $base_dir = __DIR__ . '\\PayPalCheckoutSdk\\';

    // does the class use the namespace prefix?
    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        // no, move to the next registered autoloader
        return;
    }

    // get the relative class name
    $relative_class = substr($class, $len);

    // replace the namespace prefix with the base directory, replace namespace
    // separators with directory separators in the relative class name, append
    // with .php
    $file = $base_dir . str_replace('\\', '\\', $relative_class) . '.php';

    // if the file exists, require it
    if (file_exists($file)) {
        require $file;
    }
});
```
With this autoloader 2 files has been successfully loaded:

> C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\SandboxEnvironment.php
> C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\PayPalEnvironment.php

And next step is trying load this class:
**PayPalHttp\Environment**
with error:

> Fatal error: Interface 'PayPalHttp\Environment' not found in C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\PayPalEnvironment.php on line 7

**Comment by tiffanyrzhou** [comment]
Hello @MESWEB. Thanks for reaching out. Is there a reason why you are not using composer? PayPalHttp is a new dependency to replace BraintreeHTTP.

**Comment by MESWEB** [comment]
Hi @tiffanyrzhou.
Yes it's very big reason:

My own loader
> autoload.php **309 bytes**

And here is composer:
> composer.phar **1,874,955 bytes**

My own autoloader works very great without unnecessary code. Look for google there are lot info about minimize HTML code by deleting unused CSS or JS and many more so what's a reason why I should use composer which one is very big.

I resolve my problem by download PayPalHttp script and add it to my lib folder now autoloader read all necessary files without problem.

**Comment by tiffanyrzhou** [comment]
@MESWEB Thank you for the explanation. Is there something that we could have done differently to improve your experience integrating with the Checkout SDK Version 1.0.1. Thanks!

**Comment by MESWEB** [comment]
@tiffanyrzhou yes it's many things. Please add own autoload Class:
```php
<?php

define('ROOT', __DIR__ . DIRECTORY_SEPARATOR);
define('SRC', ROOT . 'paypal\rest-api-sdk-php\lib' . DIRECTORY_SEPARATOR);

spl_autoload_register(function ($class) {
    $file = SRC . str_replace('\\', '/', $class) . '.php';
    if (file_exists($file)) {
        require $file;
    }
});
```
And add missing files to lib folder like PayPalHttp etc.
I just start playing now with this SDK so later I will discover something more.

**Comment by thinkstudeo** [comment]
@tiffanyrzhou 
Please add the new release to the [docs](https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/). It still suggests to pull in `v1.0.0`. And the way it is written it will not pull in any fixes/minor updates. It should have ideally been documented as 
```bash
//Create a PHP project in your directory, then run the following command to install the PayPal JavaScript SDK.
composer require paypal/paypal-checkout-sdk:1.*
```
OR add the following to the `require` key of your project `composer.json`

```json
{
    "require": {
         "paypal/paypal-checkout-sdk": "^1.0"
    }
}
```

And then run

```bash
composer update
```

**Comment by omar09091993** [comment]
> ### General information
> * SDK/Library version: 1.0.1
> * Environment: Sandbox
> * `PayPal-Debug-ID` values:
> * Language, language version, and OS: PHP Windows 10
> 
> ### Issue description
> I can't autoload files without composer.
> **index.php**
> 
> ```
> <?php
> 
> require __DIR__ . '\autoload.php';
> 
> use PayPalCheckoutSdk\Core\PayPalHttpClient;
> use PayPalCheckoutSdk\Core\SandboxEnvironment;
> // Creating an environment
> $clientId = "xxx";
> $clientSecret = "xxx";
> 
> $environment = new SandboxEnvironment($clientId, $clientSecret);
> $client = new PayPalHttpClient($environment);
> ```
> 
> **autoload.php**
> 
> ```
> <?php
> /**
>  * An example of a project-specific implementation.
>  *
>  * After registering this autoload function with SPL, the following line
>  * would cause the function to attempt to load the \Foo\Bar\Baz\Qux class
>  * from /path/to/project/src/Baz/Qux.php:
>  *
>  *      new \Foo\Bar\Baz\Qux;
>  *
>  * @param string $class The fully-qualified class name.
>  * @return void
>  */
> spl_autoload_register(function ($class) {
> 
>     // project-specific namespace prefix
>     $prefix = 'PayPalCheckoutSdk\\';
> 
>     // base directory for the namespace prefix
>     $base_dir = __DIR__ . '\\PayPalCheckoutSdk\\';
> 
>     // does the class use the namespace prefix?
>     $len = strlen($prefix);
>     if (strncmp($prefix, $class, $len) !== 0) {
>         // no, move to the next registered autoloader
>         return;
>     }
> 
>     // get the relative class name
>     $relative_class = substr($class, $len);
> 
>     // replace the namespace prefix with the base directory, replace namespace
>     // separators with directory separators in the relative class name, append
>     // with .php
>     $file = $base_dir . str_replace('\\', '\\', $relative_class) . '.php';
> 
>     // if the file exists, require it
>     if (file_exists($file)) {
>         require $file;
>     }
> });
> ```
> 
> With this autoloader 2 files has been successfully loaded:
> 
> > C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\SandboxEnvironment.php
> > C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\PayPalEnvironment.php
> 
> And next step is trying load this class:
> **PayPalHttp\Environment**
> with error:
> 
> > Fatal error: Interface 'PayPalHttp\Environment' not found in C:\xampp\htdocs\paypal\PayPalCheckoutSdk\Core\PayPalEnvironment.php on line 7

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback. We have heard from the Github Community to provide an implementation without using composer and will look to incorporate it in future releases. At this time we do not have any update on when this might become available.
Here are some information that can be used to create your own autoload class
paypalhttp github library: https://github.com/paypal/paypalhttp_php
paypalhttp packagist link:https://packagist.org/packages/paypal/paypalhttp
Instruction Guide:
https://ehikioya.com/how-to-install-php-packages-without-composer/
