### ISSUE TITLE
This SDK uses archived BraintreeHttp repo, does it pose any time limit from support point of view

### ISSUE THREAD

**Issue by thinkstudeo** [paypal/Checkout-PHP-SDK#39]
While digging through the SDK code for better understanding the data format of response from the Orders API, I could see that under the hood this SDK uses BraintreeHttp repo.

To further dig the data type format I visited the [BraintreeHttp repo on github](https://github.com/braintree/braintreehttp_php). It shows that the repo has been archived.

So my question: how long will this SDK be supported by Paypal? Should I use this SDK if the project requirement is a minimum support for 5 years? Or should I build my own REST api client for fulfilling the requirement of minimum 5 year support?

@ganeshramc I would really appreciate a response to this as I am skeptical about the base repo being archived (BraintreeHttp) as well as there not being any activity since months on the current repo as well.

**Comment by ganeshramc** [comment]
Hey @thinkstudeo we have moved to paypalhttp in the latest release and we plan to support this in the future. Thanks!

**Comment by thinkstudeo** [comment]
@ganeshramc Thanks for the response.
However It has been responded after almost a month. Is there any other channel to receive a response within reasonable time which I have missed reading?
Meanwhile I did dig through the code and learnt about paypalhttp. Thanks
