### ISSUE TITLE
Support for meta info when creating order and in webhook event response

### ISSUE THREAD

**Issue by thinkstudeo** [paypal/Checkout-PHP-SDK#41]
### Request for enhancement/feature: Support for meta information

When creating new order for any transaction currently there is no provision to include any kind of meta information.

It would be nice to have a property/field for meta information when the payment is created for eg:

```php
'meta' => [
    'cart_id' => 'SOMECARTID'
]
```
maybe via a `setMeta()` method 

```php
public function setMeta(array $meta)
{
    $this->meta = array_merge($this->meta, $meta);
}

public function getMeta()
{
    return $this->meta;
}

/** 
  * Can then be used to add meta info when creating payment 
  * And then when webhook event response is returned
  * This meta info is returned in the event response
  */
$this->setMeta([
    'cart_id' => 'SOMECARTID',
    'order_no' => '123456'
]);
```
And then when a webhook is subscribed for eg: PAYMENT.CAPTURE.COMPLETED the webhook event response returns this meta information within the response.
```json
{
    "meta": {
        "cart_id": "SOMECARTID",
        "order_id": 123456
    }
}
```
This would help in tracking down the record (database) corresponding to the captured event easily.

Currently the tracking has to be done via the payment/resource id returned by the webhook event response - which means to create one more index on the database on the payment_id column.

Ability to add and get meta information in webhook event response will help simplify the process of reconciliation.

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback. Our Order API currently do not support Order metadata. We will take this into consideration for future development work.
