### ISSUE TITLE
Verification of custom payee

### ISSUE THREAD

**Issue by MESWEB** [paypal/Checkout-PHP-SDK#42]
Where I can check payee status before authenticate payment? Verified or not?
```php
"payee" => [
            "email_address" =>  $custom_email,
        ],
```
This should be like that:
```php
"payee" => [
            "email_address" =>  $custom_email,
            "status" => 'check'
        ],
```
and response should be like this:
```php
 [email_address] => xxx@xxx.pr
 [status] => not verified their account and is located outside the US.
```

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback. Our APIs currently do not support verification of payee status.
