### ISSUE TITLE
HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"} 

### ISSUE THREAD

**Issue by lse123** [paypal/Checkout-PHP-SDK#48]
At
http://www.yyyyyy.com/GetOrder.php
getting? why error?
https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/
PHP . // Where put this >>> ???
$request = new OrdersCreateRequest();
$request->headers["prefer"] = "return=representation";

error

Fatal error: Uncaught PayPalHttp\HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"} in /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php:215 Stack trace: #0 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php(100): PayPalHttp\HttpClient->parseResponse(Object(PayPalHttp\Curl)) #1 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Core/AuthorizationInjector.php(37): PayPalHttp\HttpClient->execute(Object(PayPalCheckoutSdk\Core\AccessTokenRequest)) #2 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Core/AuthorizationInjector.php(29): PayPalCheckoutSdk\Core\AuthorizationInjector->fetchAccessToken() #3 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php(64): PayPalCheckoutSdk\Core\AuthorizationInjector->inject(Object(PayPalCheckoutSdk\Orders\OrdersGetRequest)) #4 /ho in /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php on line 215

code
```
<?php

namespace Sample;

require __DIR__ . '/vendor/autoload.php';
//1. Import the PayPal SDK client that was created in `Set up Server-Side SDK`.
use Sample\PayPalClient;
use PayPalCheckoutSdk\Orders\OrdersGetRequest;
use Sample\CaptureIntentExamples\CreateOrder;

class GetOrder
{

  // 2. Set up your server to receive a call from the client
  /**
   *You can use this function to retrieve an order by passing order ID as an argument.
   */
  public static function getOrder($orderId)
  {

    // 3. Call PayPal to get the transaction details
    $client = PayPalClient::client();
    $response = $client->execute(new OrdersGetRequest($orderId));
    /**
     *Enable the following line to print complete response as JSON.
     */
    //print json_encode($response->result);
    print "Status Code: {$response->statusCode}\n";
    print "Status: {$response->result->status}\n";
    print "Order ID: {$response->result->id}\n";
    print "Intent: {$response->result->intent}\n";
    print "Links:\n";
    foreach($response->result->links as $link)
    {
      print "\t{$link->rel}: {$link->href}\tCall Type: {$link->method}\n";
    }
    // 4. Save the transaction in your database. Implement logic to save transaction to your database for future reference.
    print "Gross Amount: {$response->result->purchase_units[0]->amount->currency_code} {$response->result->purchase_units[0]->amount->value}\n";

    // To print the whole response body, uncomment the following line
    // echo json_encode($response->result, JSON_PRETTY_PRINT);
  }
}

/**
 *This driver function invokes the getOrder function to retrieve
 *sample order details.
 *
 *To get the correct order ID, this sample uses createOrder to create a new order
 *and then uses the newly-created order ID with GetOrder.
 */
if (!count(debug_backtrace()))
{
  GetOrder::getOrder('9EC1989552495262M', true);  // REPLACE-WITH-ORDER-ID  
}

```

**Comment by lse123** [comment]
is this ok????

```
<?php

namespace Sample;

use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;

ini_set('error_reporting', E_ALL); // or error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

class PayPalClient
{
    /**
     * Returns PayPal HTTP client instance with environment that has access
     * credentials context. Use this instance to invoke PayPal APIs, provided the
     * credentials have access.
     */
    public static function client()
    {
        return new PayPalHttpClient(self::environment());
    }

    /**
     * Set up and return PayPal PHP SDK environment with PayPal access credentials.
     * This sample uses SandboxEnvironment. In production, use LiveEnvironment.
     */
    public static function environment()
    {
       $clientId = getenv("CLIENT_ID") ?: "<>";
       $clientSecret = getenv("CLIENT_SECRET") ?: "<>";

        return new LiveEnvironment($clientId, $clientSecret);
    }
}
```

**Comment by pabloldeoliveira** [comment]
@Ise123 yes, you have to use the class PayPalClient first in order to GetOrder to work.

**Comment by lse123** [comment]
I want to get order from orderID as real appear as two orders 0.01... so live/production env...
What do you mean? I followed the guide... 
used:
use Sample\PayPalClient;
but look here:

   /**
     * Set up and return PayPal PHP SDK environment with PayPal access credentials.
     * This sample uses **SandboxEnvironment**. In production, use **LiveEnvironment**.
     */
    public static function environment()
    {
       $clientId = getenv("CLIENT_ID") ?: "<>";
       $clientSecret = getenv("CLIENT_SECRET") ?: "<>";

        return new **LiveEnvironment**($clientId, $clientSecret);
    }

and here in GitHub code at https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/PayPalClient.php

   /**
     * Setting up and Returns PayPal SDK environment with PayPal Access credentials.
     * For demo purpose, we are using SandboxEnvironment. In production this will be
     * **ProductionEnvironment**.
     */
    public static function environment()
    {
        $clientId = getenv("CLIENT_ID") ?: "<<PAYPAL-CLIENT-ID>>";
        $clientSecret = getenv("CLIENT_SECRET") ?: "<<PAYPAL-CLIENT-SECRET>>";
        return new **SandboxEnvironment**($clientId, $clientSecret);

**Comment by ShaBax** [comment]
Same issue 
Here is my code 
```
$environment = new SandboxEnvironment($clientId, $clientSecret);
$client = new PayPalHttpClient($environment);
$response = $payPalHttpClient->execute(new OrdersGetRequest($orderId));
```

1. create  SandboxEnvironment ( When I tried to print environment variable its empty)
2. create PayPalHttpClient using environment, check the output:
```
{
  "authInjector": {
    "accessToken": null
  },
  "environment": {
    
  },
  "injectors": [
    {
      "accessToken": null
    },
    {
      
    },
    {
      
    }
  ],
  "encoder": {
    
  },
  "curlCls": "PayPalHttp\\Curl"
}
```
3. execute payPalHttpClient output:

`{"error":"invalid_client","error_description":"Client Authentication failed"}`

**Comment by ShaBax** [comment]
any solution?

**Comment by gs63875** [comment]
I have the same issue. Does anyone have solution?

**Comment by tiffanyrzhou** [comment]
> I have the same issue. Does anyone have a solution?

Hello @gs63875 . Can you see if the solution I provided to @ShaBax https://github.com/paypal/Checkout-PHP-SDK/issues/52 works for you?

**Comment by tiffanyrzhou** [comment]
Hello @lse123 .

1.  Can you see if the solution provided at https://github.com/paypal/Checkout-PHP-SDK/issues/52 works for you?
2.  https://github.com/paypal/Checkout-PHP-SDK/tree/develop/samples
You can refer to either the authorizeIntent or captureIntent example's run all file to get see a possible integration method. For get order: Try `$order = GetOrder::getOrder($orderId);`

**Comment by lse123** [comment]
is the below code for sandbox only? If yes, what is the code for production?

https://github.com/paypal/Checkout-PHP-SDK/tree/develop/samples

`<?php

namespace Sample;

use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;

ini_set('error_reporting', E_ALL); // or error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

class PayPalClient
{
    /**
     * Returns PayPal HTTP client instance with environment which has access
     * credentials context. This can be used invoke PayPal API's provided the
     * credentials have the access to do so.
     */
    public static function client()
    {
        return new PayPalHttpClient(self::environment());
    }
    
    /**
     * Setting up and Returns PayPal SDK environment with PayPal Access credentials.
     * For demo purpose, we are using SandboxEnvironment. In production this will be
     * ProductionEnvironment.
     */
    public static function environment()
    {
        $clientId = getenv("CLIENT_ID") ?: "<<PAYPAL-CLIENT-ID>>";
        $clientSecret = getenv("CLIENT_SECRET") ?: "<<PAYPAL-CLIENT-SECRET>>";
        return new SandboxEnvironment($clientId, $clientSecret);
    }
}`

**Comment by ShaBax** [comment]
@lse123
As its saying in docs
```
/**
 * Setting up and Returns PayPal SDK environment with PayPal Access credentials.
 * For demo purpose, we are using SandboxEnvironment. In production this will be
 * ProductionEnvironment.
 */
```
 use ProductionEnvironment instead of SandboxEnvironment for the production.

`return new ProductionEnvironment($clientId, $clientSecret);`

and don't forget to include in the header
`use PayPalCheckoutSdk\Core\ProductionEnvironment;`

**Comment by lse123** [comment]
Fatal error: Uncaught PayPalHttp\HttpException: {"error":"invalid_client","error_description":"Client Authentication failed"} in /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php:215 Stack trace: #0 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php(100): PayPalHttp\HttpClient->parseResponse(Object(PayPalHttp\Curl)) #1 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Core/AuthorizationInjector.php(37): PayPalHttp\HttpClient->execute(Object(PayPalCheckoutSdk\Core\AccessTokenRequest)) #2 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypal-checkout-sdk/lib/PayPalCheckoutSdk/Core/AuthorizationInjector.php(29): PayPalCheckoutSdk\Core\AuthorizationInjector->fetchAccessToken() #3 /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php(64): PayPalCheckoutSdk\Core\AuthorizationInjector->inject(Object(PayPalCheckoutSdk\Orders\OrdersGetRequest)) #4 /ho in /home/polislatchiaptsv/public_html/main/vendor/paypal/paypalhttp/lib/PayPalHttp/HttpClient.php on line 215


```
<?php

namespace Sample;

require __DIR__ . '/vendor/autoload.php';
//1. Import the PayPal SDK client that was created in `Set up Server-Side SDK`.
use Sample\PayPalClient;
use PayPalCheckoutSdk\Orders\OrdersGetRequest;
use Sample\CaptureIntentExamples\CreateOrder;

class GetOrder
{

  // 2. Set up your server to receive a call from the client

  public static function getOrder($orderId)
  {

    // 3. Call PayPal to get the transaction details
    $client = PayPalClient::client();
    $response = $client->execute(new OrdersGetRequest($orderId));
   
    //print json_encode($response->result);
    print "Status Code: {$response->statusCode}\n";
    print "Status: {$response->result->status}\n";
    print "Order ID: {$response->result->id}\n";
    print "Intent: {$response->result->intent}\n";
    print "Links:\n";
    foreach($response->result->links as $link)
    {
      print "\t{$link->rel}: {$link->href}\tCall Type: {$link->method}\n";
    }
   
    print "Gross Amount: {$response->result->purchase_units[0]->amount->currency_code} {$response->result->purchase_units[0]->amount->value}\n";

    // To print the whole response body, uncomment the following line
    // echo json_encode($response->result, JSON_PRETTY_PRINT);
  }
}


if (!count(debug_backtrace()))
{
  GetOrder::getOrder('9EC1989552495262M', true);  // REPLACE-WITH-ORDER-ID 
}
?>


```

**Comment by lse123** [comment]
SAME getting with

<?php

namespace Sample;


use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\SandboxEnvironment;
use PayPalCheckoutSdk\Core\ProductionEnvironment;

ini_set('error_reporting', E_ALL); // or error_reporting(E_ALL);
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

class PayPalClient
{
    
    public static function client()
    {
        return new PayPalHttpClient(self::environment());
    }

    public static function environment()
    {
       $clientId = getenv("CLIENT_ID") ?: "";
       $clientSecret = getenv("CLIENT_SECRET") ?: "";

        return new ProductionEnvironment($clientId, $clientSecret);

**Comment by tiffanyrzhou** [comment]
Hello @lse123 , 

Can you share me the Paypal-Debug-Id and which environment you are trying to run this in? (sandbox vs production)? Please refer to the following code to print the headers of an exception. There you can find the  Paypal-Debug-Id.

```php
public static function createOrder($debug=false)
    {

        try{
            $request = new OrdersCreateRequest();
            $request->headers["prefer"] = "return=representation";
            $request->body = self::buildRequestBody();
            $client = PayPalClient::client();
            $response = $client->execute($request);
            print_r($response->headers);
            if ($debug)
            {
                print "Status Code: {$response->statusCode}\n";
                print "Status: {$response->result->status}\n";
                print "Order ID: {$response->result->id}\n";
                print "Intent: {$response->result->intent}\n";
                print "Links:\n";
                foreach($response->result->links as $link)
                {
                    print "\t{$link->rel}: {$link->href}\tCall Type: {$link->method}\n";
                }
                // To toggle printing the whole response body comment/uncomment below line
                echo json_encode($response->result, JSON_PRETTY_PRINT), "\n";
            }
            return $response;
        } catch(HttpException $e) {
            print_r($e->headers);
        }
    }

```

**Comment by lse123** [comment]
WHERE PUT this code you say
in what file???

**Comment by tiffanyrzhou** [comment]
Hello @lse123. You can put it anywhere you make a request.To get the headers of the HTTP Exception surround it with a try catch. For the example code provided I used the request from https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/GetOrder.php

**Comment by lse123** [comment]
so where put the Paypal ID of transaction production 0.01$ in code???

**Comment by gs63875** [comment]
I think i found the solution.  No need to use the Sample file to set the environment.

`use PayPalCheckoutSdk\Core\PayPalHttpClient;
use PayPalCheckoutSdk\Core\ProductionEnvironment;
use PayPalCheckoutSdk\Core\SandboxEnvironment;
use PayPalCheckoutSdk\Orders\OrdersGetRequest;

 if ($paypalProductionEnv) {
        $environment = new ProductionEnvironment($paypalClientId, $paypalSecret);
    } else {

        $environment = new SandboxEnvironment($paypalClientId, $paypalSecret);
    }

    $client = **new PayPalHttpClient($environment);**

    $response = $client->execute(new OrdersGetRequest($orderId));

    print_r($response);`

**Comment by lse123** [comment]
IS Not needed PayPal Transaction ID? If yes needed, where to put it?

**Comment by tiffanyrzhou** [comment]
@lse123 Do you mean the Paypal-Debug-Id? You do not need to put in in the request, PayPal returns it in the header of the response.
