### ISSUE TITLE
Is it possible to preauthorize and later capture an amount?

### ISSUE THREAD

**Issue by realtebo** [paypal/Checkout-PHP-SDK#51]
I am coming here from Stripe world to extends our payment systems support to Paypal

Actually when a customer place an order, we preauthorize the import , send, some days later, we effectively 'capture' the amount, doing eventually a second transaction to compensate if real evasion is higher than what requested.

I am asking you if this flow is supported, and to kindly point me to sdk documentation where it's explained.

If not, could you suggest me an alternative?

**Comment by tiffanyrzhou** [comment]
Hello @realtebo. It seems like you're talking about an AuthorizeIntentExamples. Please take a look at the following : https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/AuthorizeIntentExamples/RunAll.php

You can adjust the amount in the request body of the AuthorizationsCaptureRequest. Depending on your account settings and other factors, you can capture up to 1XX% of the original amount. 

To read more about the call to capture the authorization, you can refer to https://developer.paypal.com/docs/api/payments/v2/#authorizations_capture

**Comment by realtebo** [comment]
Thanks for pointing me to an example and to api ref.

Is there any tutorial / guide ? 

The example doesn't containt a single comment row 

For example:
https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/AuthorizeIntentExamples/RunAll.php#L31

Line 31 read something from phpinput but .. why ?!

I need some theory about authorizing and capturing moeny, for example: how many days the preauth remains valid?
