### ISSUE TITLE
{"error":"invalid_client","error_description":"Client Authentication failed"}

### ISSUE THREAD

**Issue by ShaBax** [paypal/Checkout-PHP-SDK#52]
Here is my code 
```
$environment = new SandboxEnvironment($clientId, $clientSecret);
$client = new PayPalHttpClient($environment);
$response = $payPalHttpClient->execute(new OrdersGetRequest($orderId));
```

1. create  SandboxEnvironment ( When I tried to print environment variable its empty)
2. create PayPalHttpClient using environment, check the output:
```
{
  "authInjector": {
    "accessToken": null
  },
  "environment": {
    
  },
  "injectors": [
    {
      "accessToken": null
    },
    {
      
    },
    {
      
    }
  ],
  "encoder": {
    
  },
  "curlCls": "PayPalHttp\\Curl"
}
```
3. execute payPalHttpClient output:

`{"error":"invalid_client","error_description":"Client Authentication failed"}`

**Comment by tiffanyrzhou** [comment]
Hello @ShaBax! Can you ensure that you are setting up the environment variables CLIENT_SECRET and CLIENT_ID?  One easy way to fo this is to set it up through your IDE under the run configuration. 
Alternatively, you can change the variables under the environment method in this file https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/PayPalClient.php.

**Comment by ShaBax** [comment]
@tiffanyrzhou  Thank you for the response. 
Yes, I'm setting the right credentials.  when I tried to print $environemnt its empty.
`$environment = new SandboxEnvironment($clientId, $clientSecret);`

**Comment by tiffanyrzhou** [comment]
@ShaBax  Can you try something for me. 

In this file https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/PayPalClient.php#L29
 Can you replace the code in the environment method with the following and share me the output: 

`  public static function environment()`
   ` {`
        `//$clientId = getenv("CLIENT_ID") ?: "<<PAYPAL-CLIENT-ID>>";`
       ` //$clientSecret = getenv("CLIENT_SECRET") ?: "<<PAYPAL-CLIENT-SECRET>>";`
       ` $clientId ="";`
       ` $clientSecret ="";`
        `$Senviroment =  new SandboxEnvironment($clientId, $clientSecret);`
       ` print_r($Senviroment);`
        `return $Senviroment;`
    `}`

And wherever you are create the client be sure to import PayPalClient. 
and  create a client like this:
`$client = PayPalClient::client();`

Here is an additional sample : https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/GetOrder.php

**Comment by ShaBax** [comment]
@tiffanyrzhou I tried that before, no matter what you pass to SandboxEnvironment the result is empty

**Comment by tiffanyrzhou** [comment]
Hello @ShaBax. 
In your code you provided I notice a possible error: 
`$environment = new SandboxEnvironment($clientId, $clientSecret);`
`$client = new PayPalHttpClient($environment);`
`$response = $payPalHttpClient->execute(new OrdersGetRequest($orderId)); `
The last line should be instead:
`$response = $client->execute(new OrdersGetRequest($orderId)); `

I know this doesn't resolve the problem that the 
$environment = new SandboxEnvironment($clientId, $clientSecret);  and $environment is empty. However, I am unable to reproduce that scenario on my local. 

Moving on, it would be very difficult for me to continue debugging if I can't see your code. Next step I would suggest running one of the runAll.php sample files. If you are continuing to run into problems using the samples, I can take a look again.

**Comment by gs63875** [comment]
@ShaBax, please check https://github.com/paypal/Checkout-PHP-SDK/issues/48#issuecomment-583169107

**Comment by ShaBax** [comment]
@gs63875 I already tried this as well, but no luck

**Comment by tiffanyrzhou** [comment]
@ShaBax Were you able to take a look at my suggestion?

> Hello @ShaBax.
> In your code you provided I notice a possible error:
> `$environment = new SandboxEnvironment($clientId, $clientSecret);`
> `$client = new PayPalHttpClient($environment);`
> `$response = $payPalHttpClient->execute(new OrdersGetRequest($orderId)); `
> The last line should be instead:
> `$response = $client->execute(new OrdersGetRequest($orderId)); `
> 
> I know this doesn't resolve the problem that the
> $environment = new SandboxEnvironment($clientId, $clientSecret); and $environment is empty. However, I am unable to reproduce that scenario on my local.
> 
> Moving on, it would be very difficult for me to continue debugging if I can't see your code. Next step I would suggest running one of the runAll.php sample files. If you are continuing to run into problems using the samples, I can take a look again.
