### ISSUE TITLE
Not able to get order details on Paypal sandbox after successful completion of order

### ISSUE THREAD

**Issue by giantslayer21** [paypal/Checkout-PHP-SDK#54]
I'm trying to integrate paypal checkout button to my project using REST api... Having issues on the server side when I try to save the transanction details. Any help is appreciated :)
**CLIENT SIDE CODE**
<script>
    paypal.Buttons({
      createOrder: function(data, actions) {
      // This function sets up the details of the transaction, including the amount and line item details.
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '0.01'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      return actions.order.capture().then(function(details) {
        alert('Transaction completed by ' + details.payer.name.given_name);
        // Call your server to save the transaction
        return fetch('/paypalcheckout/paypalcomplete.php', {
          method: 'post',
          headers: {
            'content-type': 'application/json'
          },
          body: JSON.stringify({
            orderID: data.orderID
          })
        });
      });
    }
    }).render('#paypal-button-container');
  </script>

**SERVER SIDE CODE**
public static function getOrder($orderId)
   {
    // 3. Call PayPal to get the transaction details
    $client = PayPalClient::client();
    $response = $client->execute(new OrdersGetRequest($orderId));
    //the statements after this aren't being executed....    
    //Trying to save the order details to my database using php
  }

None of the statements are working after the $response = ....; statement. I have tried calling my server to save the orderId in the above method . But the same thing does not even get executed after the above mentioned statement..

**Comment by KingKorg** [comment]
how the $orderId variable is called ? in $_GET ?

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out @giantslayer21? Can you help me understand the issue further? 
What environment is this issue the occurring in?
What is in the value of response?
If the response is not null, can you share some sample Paypal-Debug-Id? Thanks.
