### ISSUE TITLE
Paypal Smart Button Integration - Payment Execution

### ISSUE THREAD

**Issue by danieletulone** [paypal/Checkout-PHP-SDK#56]
Hi, I'm using smart button implementation in VueJS app and I have included this sdk in my php backend app. 

I've implemented the code found here: [Implement a PayPal Checkout Server Integration](https://developer.paypal.com/docs/archive/checkout/how-to/server-integration/#1-set-up-your-client-to-call-your-server). In onAuthorize, I have an error because paymentID has null value (only paymentID). 

Making a console.log, I've seen that there are orderID and paymentToken with same value (I think that it is the id) and paymentID has null value.

Is paymentToken/orderId the same thing of paymentID?

**Comment by tiffanyrzhou** [comment]
Please refer to this new integration guide https://developer.paypal.com/docs/business/checkout/set-up-standard-payments/
