### ISSUE TITLE
Fix the documentation. There is no "order_id" param anymore.

### ISSUE THREAD

**Issue by x-N0** [paypal/Checkout-PHP-SDK#57]
**How did I noticed the issue?**
I saw the Request params that we receive from paypal when submitting a purchase, and I didn't saw the "order_id" param in the link retrieved as you have in the example code, so I tried using the **token** param retrieved, and that was the right answer.

**What I think should be a solution?** 
I think the example in the documentation is unclear because of that, so the "APPROVED-ORDER-ID" should be changed to "RETRIEVED_TOKEN_PARAM" or "RETRIEVED_REQUEST_TOKEN". I think it would be more clear.

**Specific explanation about the issue.**
The Request I am talking about is the one retrieved from paypal when the purchase is made, so they `return` to the page that you want, and send you data in the url, example: URL:`localhost:8080/paid?token=899471095B7029804&PayerID=GW270ZXFUBDD4` **token** & **PayerID** are retrieved.

**The steps** to get the token is using: `$request->token`.

![imagen](https://user-images.githubusercontent.com/51316342/79117337-1c0db880-7d48-11ea-9298-3464f0a74978.png)
Image 1: var_dump($request) made to Request retrieved from Paypal to my web's URI as I referenced before.

**Tested using sandbox.**

The piece of documentation that I refer to:
```
use PayPalCheckoutSdk\Orders\OrdersCaptureRequest;
// Here, OrdersCaptureRequest() creates a POST request to /v2/checkout/orders
// $response->result->id gives the orderId of the order created above
$request = new OrdersCaptureRequest("APPROVED-ORDER-ID"); <---Here.
$request->prefer('return=representation');
try {
    // Call API with your client and get a response for your call
    $response = $client->execute($request);
    
    // If call returns body in response, you can get the deserialized version from the result attribute of the response
    print_r($response);
}catch (HttpException $ex) {
    echo $ex->statusCode;
    print_r($ex->getMessage());
}
```

**Comment by tiffanyrzhou** [comment]
@x-N0 Thank you for the feedback. We will look into improving our readme file. The "APPROVED-ORDER-ID" param is expecting the order_id that was returned in the create order request.
The APPROVED prefix is to indicate that an order should be approved by the buyer, before it can be captured.
