### ISSUE TITLE
how to do negative testing

### ISSUE THREAD

**Issue by shinnlu** [paypal/Checkout-PHP-SDK#62]
i usually see INSTRUMENT_DECLINED error in logs.
it was happen in callback url and trying to execute the Order Capture Request
```
$token = $request->token;
$PayerID = $request->PayerID;
$request = new OrdersCaptureRequest($token);
$request->prefer('return=representation');
$request->headers["AUTHORIZATIONID"] = 10603;
$response = '';
try {
    // INSTRUMENT_DECLINED error in this line
    $response = $this->PaypalService->client()->execute($request);
    .
    .
}
```
i have try many ways to do negative test, but all transaction was successful, i have enable 'Negative Test' in sandbox facilitator account.
how can i do testing in sandbox mode?

**Comment by rsdighe76** [comment]
Please Check - https://developer.paypal.com/docs/api-basics/sandbox/request-headers/
