### ISSUE TITLE
How to install Checkout-PHP-SDK without Composer

### ISSUE THREAD

**Issue by victor-sarabia** [paypal/Checkout-PHP-SDK#63]
Will there be a package to install the Checkout-PHP-SDK without Composer?

**Comment by tiffanyrzhou** [comment]
Thank you for reaching out and providing feedback. We have heard from the Github Community to provide an implementation without using composer and will look to incorporate it in future releases. At this time we do not have any update on when this might become available. 
Here are some information that can be used to create your own autoload class
paypalhttp github library: https://github.com/paypal/paypalhttp_php
paypalhttp packagist link:https://packagist.org/packages/paypal/paypalhttp
Instruction Guide:
https://ehikioya.com/how-to-install-php-packages-without-composer/
