### ISSUE TITLE
how to ?

### ISSUE THREAD

**Issue by cullsin** [paypal/Checkout-PHP-SDK#66]
Hello, 

I have a requirement. I have a platform and customers sends money to the platform as well as the platform sends money to the customer. I want to do it in Backend PHP REST API. Can you please suggest the list of API calls that I need to invoke. I have a basic understanding that I need to register as a merchant with PayPal.

PS: My Customers are all over the world.

Please suggest.

Thanks,
Raja K

**Comment by rsdighe76** [comment]
I believe your question can be best answered by posting it on https://www.paypal-community.com/t5/PayPal-Community/ct-p/en -
