### ISSUE TITLE
Show do not refresh message/page while payment details are fetched PayPal Checkout Button

### ISSUE THREAD

**Issue by KingKorg** [paypal/Checkout-PHP-SDK#67]
Hello I use Checkout-PHP-SDK V2 on my site

The payment button like this:

```
<script>

    paypal.Buttons({

        createOrder: function(data, actions) {

            return fetch('/createorder', {

                method: 'post'

            }).then(function(res) {

                return res.json();

            }).then(function(data) {

                return data.orderID;

            });

        },

        onApprove: function(data, actions) {

            return actions.order.capture().then(function() {

                window.location = "/getorder/" + data.orderID;

            });

        }

    }).render('#paypal-button-container');

</script>
```

it works but I want to display a message (please wait) at the closing of modal paypal so that the buyer does not close the page or refresh it otherwise it will not be redirected with window.location that I have in onApprove

Please excuse my English I did the translation from google to communicate with you.

**Comment by rajarampadmanathan** [comment]
Seems related to https://github.com/paypal/paypal-checkout-components

@bluepnume  - Can you please check this?

**Comment by KingKorg** [comment]
> Seems related to https://github.com/paypal/paypal-checkout-components
> 
> @bluepnume - Can you please check this?

hi, no I use the CreateOrder and GetOrder class of Checkout-PHP-SDK V2 
https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/CaptureIntentExamples/CreateOrder.php
https://github.com/paypal/Checkout-PHP-SDK/blob/develop/samples/GetOrder.php

**Comment by bluepnume** [comment]
Hi! Can you just do something like:

```javascript
        onApprove: function(data, actions) {
           // Display a custom message to buyer
           document.querySelector('#some-container').innerHTML = 'Message to customer';

            return actions.order.capture().then(function() {
                window.location = "/getorder/" + data.orderID;
            });
        }
```

**Comment by KingKorg** [comment]
hi bluepnume, i just saw your message that's what i did at least now i'm sure i'm on the right track thanks to you
