### ISSUE TITLE
Pulling wrong supplier ref number when using this function: public static function convertPNRefToSupplierRefNun($pnref)

### ISSUE THREAD

**Issue by jeffklay** [paypal/Checkout-PHP-SDK#68]
Hi, 

We are using this function to pull the Supplier Ref Number from Verisign: 

public static function convertPNRefToSupplierRefNun($pnref)
{
    $hex = substr($pnref, -8);
    $dec = str_pad(hexdec($hex), 10, '0', STR_PAD_LEFT); // pad the dec so it has 10 digits
    $vs_manipulator = ord(substr($pnref, 1, 1));
    $supplier_ref_num = $vs_manipulator . '' . substr($dec, 2);
    return $supplier_ref_num;
}

Is there something wrong with our code? Once we use this function its not matching the supplier ref number in the VS portal.

**Comment by tiffanyrzhou** [comment]
Hello @jeffklay. Can you provide me with more information in regards to which part of the checkout- sdk you are using?
