### ISSUE TITLE
SDK issue with sample code in README

### ISSUE THREAD

**Issue by zerocarbthirty** [paypal/Checkout-PHP-SDK#7]
Hi,

Using the sample code in the README when you click continue at: https://www.sandbox.paypal.com/webapps/hermes?flow=1-P&ulReturn=true&token=42C66363TN045482Y&country.x=US&locale.x=en_US&arc=1#/checkout/review

it just loops twice and then throws an error (on the paypal site)

Is this SDK live or should we be using the v1 version?

**Comment by rajarampadmanathan** [comment]
Looking into it...Will update shortly.

**Comment by rajarampadmanathan** [comment]
Hi.. Thanks for reporting this.
Request payload (which is given in README.md), has "redirect_url" instead of "application_context". I have updated README file and raised an PR. 

Please let us know if you face any issue.

**Comment by zerocarbthirty** [comment]
Thanks, that helps. Does the SDK offer any shortcuts for retrieving information returned from the result or do you just do things like this:

$purchase_units = $results->purchase_units[0];
$amount = $purchase_units->amount->value;

thanks!

**Comment by pengli29** [comment]
@zerocarbthirty Could you please explain a little bit on what kind of shortcuts your are looking for? Could you provide some example also? Thanks.

**Comment by ganeshramc** [comment]
Hey @zerocarbthirty, could you explain a little bit on what shortcuts you're expecting from the SDK?
If you have any other questions, we'll keep this issue open for 7 days. We'll be closing the issue after that. Thanks 😄
