### ISSUE TITLE
Hi @MuhammadAfnanZafar. Can you try the proposed solution here https://github.com/paypal/Checkout-NET-SDK/issues/48

### ISSUE THREAD

**Issue by mcb0006** [paypal/Checkout-PHP-SDK#73]
Hi @MuhammadAfnanZafar. Can you try the proposed solution here https://github.com/paypal/Checkout-NET-SDK/issues/48

_Originally posted by @tiffanyrzhou in https://github.com/paypal/Checkout-NET-SDK/issues/43#issuecomment-643582503_

What’s the number for the next OneAuth app for my account numbers to get to work with the other applications format?

**Comment by tiffanyrzhou** [comment]
@mcb0006 can you elaborate on this issue? Not sure how this is related to to the Checkout-PHP-SDKs.
