### ISSUE TITLE
When is the Paypal Subscription API integrated into PHP SDK?

### ISSUE THREAD

**Issue by q2apro** [paypal/Checkout-PHP-SDK#74]
When is the Paypal Subscription API integrated into the PHP SDK?

https://developer.paypal.com/docs/subscriptions/
https://developer.paypal.com/docs/api/subscriptions/v1/

There seems to be no official library at the moment, that can create/handle subscriptions.

I am still using the old way that pushes the user data with a form. But I need to assign customers with IDs to be able to cancel their subscriptions automatically.

**Comment by tiffanyrzhou** [comment]
Hi @q2apro. Thank you for reaching out and providing feedback. Currently we do not have plans to incorporate PayPal Subscription API as part of this SDK bundle. We have referred this request to the team that manages the Subscription API and they will look to add it as part of their roadmap.
