### ISSUE TITLE
AuthorizationsVoidRequest void the full amount and not only the remaining 

### ISSUE THREAD

**Issue by realtebo** [paypal/Checkout-PHP-SDK#76]
In our app, we preauth the total of a cart, for example 100 €

 

From the cart, we create for example, 3 distinct orders

- item 1: 70€

- item 2: 20 €

- item 3: 10 €

 

Each item is sold from a different merchant, so 

- when merchant 1 evaded item 1 we capture 70 € without using the 'final_capture' flah

- when merchant 2 evaded item 2 we capture 20 € without using the 'final_capture' flah

- merchant 3 says us he cannot ship item, so we need to 'uncapture' the 10 € 

 we tried to use  AuthorizationsVoidRequest at this point, but we loose all previously captured amount

How can we tell paypal that we have no more captures to do?

> please note that each item evasion is done at diffrent places and times so when evading item 2 we have no info about item 3. Otherwise, we know, we could use 'final_capture' flag. But actually we're not in situation to do this.

**Comment by rsdighe76** [comment]
when you say you "loose" previously captured amount what exactly is happening. the ones that you captured for merchant 1 and merchant 2 should still remain captured i.e. if you do a status check using v2/payments/captures/id it should say that it's completed but the status of authorization v2/payments/authorizations/id should change to reflect you voided it.
