### ISSUE TITLE
3rd party access help

### ISSUE THREAD

**Issue by m0bi5** [paypal/Checkout-PHP-SDK#77]
I have extensively contact technical support but they havent been helpful. I am trying to obtain transactions of a third party account after obtaining the TRANSACTION_SEARCH permission using the NVP API. Once the user logs in and grants permission, I obtain a token and a token secret. How do I use this token and secret to access transactions of the third party?

**Comment by tiffanyrzhou** [comment]
Hi @m0bi5, this sdk doesn't include the functionality of transaction search. Please refer to this documentation https://developer.paypal.com/docs/api/transaction-search/v1/ for transaction search.
For most api request you would pass the access token the authorization header
`Authorization: Bearer <Access-Token>`
https://developer.paypal.com/docs/api/reference/api-requests/#http-request-headers
