### ISSUE TITLE
Negative Testing fails always

### ISSUE THREAD

**Issue by Georgyge** [paypal/Checkout-PHP-SDK#78]
Hii,
  I am using Checkout-PHPSDK for my paypal integration. In the order capture, if debug the response, it is always 201. Whether the status code will be other values, if there is some error. How can I test this.

`$request = new OrdersCaptureRequest("APPROVED-ORDER-ID");
$request->prefer('return=representation');
$request->headers["PayPal-Mock-Response"] = 'DUPLICATE_INVOICE_ID';
$response = $client->execute($request);`

But always the response code is 201. 

![image](https://user-images.githubusercontent.com/18278048/86203853-a74a5d80-bb83-11ea-959d-bed7fffa423d.png)

How can I check the error responses using this SDK?

**Comment by tiffanyrzhou** [comment]
Hi @Georgyge the value for the header should actually be {"mock_application_codes": "POSTAL_CODE_REQUIRED"}. 
Sample Code: 
`$request->headers["PayPal-Mock-Response"] = "{\"mock_application_codes\": \"POSTAL_CODE_REQUIRED\"}";`

Note that specific errors are for specific endpoints. `DUPLICATE_INVOICE_ID ` would only work for the create order endpoint, while COMPLIANCE_VIOLATION would only work for capture endpoint.
