### ISSUE TITLE
Not verifying payee

### ISSUE THREAD

**Issue by Georgyge** [paypal/Checkout-PHP-SDK#79]
Hii,
  I have added the email address of payee in payee email section. The payee email which I entered was wrong. Such an email did not exist in my sandbox paypal account. But when I try to pay, the capture request status code is 201. So what my question is,
1) Whether this will not validate the payee?? If not, how can we manage this in real scenario ie live case.? 
2) How to mock the insufficient fund case using this sdk?

![image](https://user-images.githubusercontent.com/18278048/86743887-d61a7500-c056-11ea-873b-793ba2be9b26.png)

**Comment by tiffanyrzhou** [comment]
@Georgyge  Can you share a paypal-debug-id. ( it should  be in the header of the response),so we can look into reproducing the issue? Depending on the integration type/ account setting, the behavior is slightly different. 

Orders API doesn't have a insufficient fund error case, please consider using the error code.`PAYER_CANNOT_PAY `
For negative testing, pass in the following header: value pair in the request.
`PayPal-Mock-Response: {"mock_application_codes": "PAYER_CANNOT_PAY"}`
