### ISSUE TITLE
'BraintreeHttp\Environment' not found

### ISSUE THREAD

**Issue by PsuFan** [paypal/Checkout-PHP-SDK#8]
Hello,

This SDK extends BraintreeHttp repo which isnt mentioned in the install guide... I recommend it be included.

> Fatal error: Interface 'BraintreeHttp\Environment' not found in PayPalCheckoutSdk\Core\PayPalEnvironment.php on line 7

https://github.com/braintree/braintreehttp_php

**Comment by rajarampadmanathan** [comment]
HI @PsuFan - than you for reporting the issue. Can you please explain how you're installing the SDK?
I installed using composer and it automatically brings the braintree dependency. I doesn't needs to be installd explicitly.

![image](https://user-images.githubusercontent.com/20119930/53764063-25f49500-3e81-11e9-9c6c-17671483352c.png)

**Comment by PsuFan** [comment]
I just downloaded and copied the files to my server manually. I don't have composer.

**Comment by rajarampadmanathan** [comment]
Okay. For this SDK dependency is managed through composer. Even after cloning this repo, we have to perform `composer install` to bring get the required dependency.

**Comment by PsuFan** [comment]
Its very easy to download and copy the two repos too though for people that don't have composer. Might be nice to add instructions for composerless people!

require autoload.php

autoload.php:
```
spl_autoload_register(function ($class) {
	$a = [
		['PayPalCheckoutSdk\\', '/PayPalCheckoutSdk/'],
		['BraintreeHttp\\', '/PayPalCheckoutSdk/BraintreeHttp/']
	];
	
	for ($i = 0; $i < count($a); $i++) {
		$len = strlen($a[$i][0]);
		if (strncmp($a[$i][0], $class, $len) === 0) {
			$base_dir = __DIR__ . $a[$i][1];
			$relative_class = substr($class, $len);
			$file = $base_dir . str_replace('\\', '/', $relative_class) . '.php';

			if (file_exists($file)) {
				require $file;
			}
			return;
		}
	}
});
```

**Comment by ganeshramc** [comment]
Hi @PsuFan, we'll definitely take your enhancement into consideration.
If you have any other questions, we'll keep this issue open for 7 days. We'll be closing the issue after that. Thanks 😄
