### ISSUE TITLE
Please include the composer install information

### ISSUE THREAD

**Issue by chateaux** [paypal/Checkout-PHP-SDK#80]
Hi,

I would love to use the SDK's, been struggling to work out how to install with composer. Would be great if this were explained in the description.

Thanks!

**Comment by chateaux** [comment]
So this is what I used to install the PHP sdk:  composer require "paypal/rest-api-sdk-php:*"

**Comment by tiffanyrzhou** [comment]
Will update the documentation include this information:
You can use the following command in the terminal
_composer require paypal/paypal-checkout-sdk_
or 
_paypal/paypal-checkout-sdk_ under the require section of your composer.json file
