### ISSUE TITLE
Error on loading paypal button with new v2 sdk

### ISSUE THREAD

**Issue by targor** [paypal/Checkout-PHP-SDK#81]
I am getting this error:

DevTools failed to load SourceMap: Could not load content for https://www.sandbox.paypal.com/smart/smart-payment-buttons.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Indeed, this url does not exist...

I am getting it on loading the button (used the tutorial)... here is my code:

`
paypal.Buttons({ 
 createOrder: function() {

	  return fetch('pay.php', {
		method: 'post',
		headers: {
		  'content-type': 'application/json'
		}
	  }).then(function(res) {
		return res.json();
	  }).then(function(data) {
		return data.id;
	  });
	}
  }).render('#paypal-button-container');

`

**Comment by tiffanyrzhou** [comment]
@targor Were you able to resolve this issue?

**Comment by targor** [comment]
Not really. Ther problem seems to come from the button itself. It even pops up if i use a html page with only the button on it. The button still works tho. I think it could be resolved if the file that the button wants to load will be provided by your server, as the file itself is not available anymore.

You can see the error when you go on the paypal button integration side, as the button is throwing the error always :D 

https://www.paypal.com/buttons/smart?flowloggingId=2b1df455f7d9e
Just open your debugger and it should appear after some seconds

**Comment by tiffanyrzhou** [comment]
@targor Thanks for reaching out and providing feedback. I have reached out the corresponding team about this issue. They've suggested to file an issue over at the paypal-checkout-components,  so they can triage it over there. They would have more context over there. https://github.com/paypal/paypal-checkout-components/issues/new/choose  Thanks!
