### ISSUE TITLE
Error in tutorial for serverside php integration

### ISSUE THREAD

**Issue by targor** [paypal/Checkout-PHP-SDK#82]
The tutorial (https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/#on-the-server)

states, that in the createorder methdo the values should be returned with:

```
// 4. Return a successful response to the client.
return $response;
}
```

but in fact, it must be returned with:

`echo json_encode($response->result, JSON_PRETTY_PRINT);`

if not, the clientside javascript wont work at all..

**Comment by tiffanyrzhou** [comment]
@targor  Closing this issue as this is a duplicate https://github.com/paypal/Checkout-PHP-SDK/issues/85. Will continue tracking the issue over at that end. Thanks!
