### ISSUE TITLE
No valid address in api capture payer response

### ISSUE THREAD

**Issue by targor** [paypal/Checkout-PHP-SDK#83]
"payer": {
        "name": {
            "given_name": "Peter",
            "surname": "<removed>"
        },
        "email_address": "<removed>",
        "payer_id": "HEU6X43KU231",
        "address": {
            "country_code": "DE"
        }
    },

reffering to this:  https://www.paypal-community.com/t5/Merchant-Products-and-Services/Missing-Payer-Address-with-Orders-API-V2-Sandbox/m-p/1946244

**Comment by tiffanyrzhou** [comment]
Hi @targor. Can you share some paypal-debug-id of the capture response?

**Comment by targor** [comment]
the problem happens on every response, even when there is a address set in the developer account.. here is a complete response for you:

{
    "id": "0K357757SK2681405",
    "purchase_units": [
        {
            "reference_id": "a hashed reference id",
            "shipping": {
                "name": {
                    "full_name": "John Doe"
                },
                "address": {
                    "address_line_1": "ESpachstr. 1",
                    "admin_area_2": "Freiburg",
                    "admin_area_1": "Baden-W\u00fcrttemberg",
                    "postal_code": "79111",
                    "country_code": "DE"
                }
            },
            "payments": {
                "captures": [
                    {
                        "id": "47731419LA209024J",
                        "status": "COMPLETED",
                        "amount": {
                            "currency_code": "EUR",
                            "value": "2.00"
                        },
                        "final_capture": true,
                        "seller_protection": {
                            "status": "ELIGIBLE",
                            "dispute_categories": [
                                "ITEM_NOT_RECEIVED",
                                "UNAUTHORIZED_TRANSACTION"
                            ]
                        },
                        "seller_receivable_breakdown": {
                            "gross_amount": {
                                "currency_code": "EUR",
                                "value": "2.00"
                            },
                            "paypal_fee": {
                                "currency_code": "EUR",
                                "value": "0.39"
                            },
                            "net_amount": {
                                "currency_code": "EUR",
                                "value": "1.61"
                            }
                        },
                        "links": [
                            {
                                "href": "https:\/\/api.sandbox.paypal.com\/v2\/payments\/captures\/47731419LA209024J",
                                "rel": "self",
                                "method": "GET"
                            },
                            {
                                "href": "https:\/\/api.sandbox.paypal.com\/v2\/payments\/captures\/47731419LA209024J\/refund",
                                "rel": "refund",
                                "method": "POST"
                            },
                            {
                                "href": "https:\/\/api.sandbox.paypal.com\/v2\/checkout\/orders\/0K357757SK2681405",
                                "rel": "up",
                                "method": "GET"
                            }
                        ],
                        "create_time": "2020-07-10T22:18:47Z",
                        "update_time": "2020-07-10T22:18:47Z"
                    }
                ]
            }
        }
    ],
    "payer": {
        "name": {
            "given_name": "John",
            "surname": "Doe"
        },
        "email_address": "sb-iw7tq2520844@personal.example.com",
        "payer_id": "4MFUJFKDVQWGL",
        "address": {
            "country_code": "DE"
        }
    },
    "links": [
        {
            "href": "https:\/\/api.sandbox.paypal.com\/v2\/checkout\/orders\/0K357757SK2681405",
            "rel": "self",
            "method": "GET"
        }
    ],
    "status": "COMPLETED"
}

**Comment by tiffanyrzhou** [comment]
Thanks @targor. I was able to reproduce this issue and assigned the corresponding team to take this further.

**Comment by targor** [comment]
That sounds good. Can you say, if this only happens on the dev test version, or does the error also happening when live?

**Comment by tiffanyrzhou** [comment]
@targor Spot checked a couple of live logs, seems like live environment is also returning a payer without the full address. Live environment response would be the same as the sandbox environment.

**Comment by targor** [comment]
Thats not good. How can i then get the address of the buyer when my order shipment is set to digital goods? (then no shipment address is shown that maybe could be used).

I need the address when creating invoices.

Is there another possibility to get the address of the buyer? Or do i need to better implement the v1 api?

**Comment by tiffanyrzhou** [comment]
@targor I have reached out to the team in regards to this issue. The request for address of the payer is considered an additional information request. You would need to reach out to PayPal technical support to enable to receiving the billing address in the capture response for both sandbox and production.
Thanks!
