### ISSUE TITLE
delete created not captured orders from PayPal

### ISSUE THREAD

**Issue by SeyamMs** [paypal/Checkout-PHP-SDK#84]
Hi folks,

Nice work everyone, I am using the PayPal php sdk to store order details on my server and it is working sleekly.

my question is when users hit the pay button I create order on PayPal then I store it in my table but some users may not complete the payment so I use the stored record to let them complete it later and this also works fine but as they can complete the order I want them to be able to delete the order too. Yes I delete it from my table and everything is fine but I do feel bad for PayPal, I checked the samples here and I could not find OrdersDeleteRequest and also in the core classes should I do post request by myself or does PayPal automatically delete them?

**Comment by tiffanyrzhou** [comment]
Hi @SeyamMs. Any order that doesn't get completed, within a set amount of time, will automatically expire. The default amount of time is 3 hours.
