### ISSUE TITLE
Notification email to payee

### ISSUE THREAD

**Issue by Georgyge** [paypal/Checkout-PHP-SDK#87]
Hi @tiffanyrzhou 
    Is it possible to send notification email with this SDK?? I have enabled the notification session in sandbox, but no email is received to the payee. 
![picturemessage_4eis0l1d q0g](https://user-images.githubusercontent.com/18278048/88179196-272a8b80-cc49-11ea-9bce-fa6da6869302.png)

This is how I enabled the notifications. Is this is the correct way?

**Comment by tiffanyrzhou** [comment]
@Georgyge Where are you checking for the email notification? If you login to developer portal and navigate to sandbox/notification you should be able to see the emails sent/recieved.
![Screen Shot 2020-07-22 at 3 39 40 PM](https://user-images.githubusercontent.com/13946076/88236386-be83e480-cc31-11ea-9400-bc6a74a9c48d.png)

**Comment by Georgyge** [comment]
@tiffanyrzhou 
  Ok Thank you. So in sandbox emails will not be send. And when it is live environment, merchant email will be send by default, right?? We did not have to do anything more like IPN setting, any other configurations and all. Am I correct?

**Comment by tiffanyrzhou** [comment]
@Georgyge Emails are sent as long as the the merchant account is configured to receive these notification, just like the settings  in screenshot you provided.  I believe the IPN setup is more for automated backend setup. When you created this app a corresponding sandbox merchant account is created, so when the emails are "sent" they go to the sandbox email.
