### ISSUE TITLE
No payer address in API Reply @tiffanyrzhou 

### ISSUE THREAD

**Issue by targor** [paypal/Checkout-PHP-SDK#88]
I found out that you can set the address response in the advanced settings of the sandbox account.. maybe it would be nice if you could add this information somwhere in the api so that this issue is not opened again:

Go to the SANDBOX APP SETTINGS -> onnect with PayPal (formerly Log In with PayPal)Identity service that enables your customers to connect with their PayPal login. -> Advanced Options.

There the addres sinfo can beactivated.

also found this:
https://wordpress.org/support/topic/require-billing-address/

**Comment by tiffanyrzhou** [comment]
@targor  Thanks for the feedback. I have submitted a request to update the documentation.
