### ISSUE TITLE
Server integration - Order created successfully but transaction not displayed in merchant account

### ISSUE THREAD

**Issue by punramesh** [paypal/Checkout-PHP-SDK#9]
Created the server call integration using following example:
https://developer.paypal.com/docs/checkout/reference/server-integration/set-up-transaction/

Order created successfully. But the transaction is not being displayed in sandbox merchant account.

**Comment by rajarampadmanathan** [comment]
Hi @punramesh - 
Please note below points:-
If you're using `CAPTURE` intent, transaction will be shown in account only after capture.
If you're using `AUTHORIZE` intent, transaction will be shown in account only after authorize.

If the transaction is not displayed even after please provide the debug id , i will check it.

**Comment by rajarampadmanathan** [comment]
@punramesh - Any update on this?

**Comment by ganeshramc** [comment]
Hi @punramesh, do we have any update on this? 
If the issue was resolved and if you have any other questions, we'll keep this issue open for 7 days. We'll be closing the issue after that. Thanks 😄
